# run with `sudo ansible-playbook i3.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Install i3 and dependencies
      apt:
        name: [
          i3, i3blocks, bc, alsa-utils, pulseaudio, rxvt-unicode,
          brightnessctl
        ]
        state: present
