# run with `sudo ansible-playbook install-packages.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Copy extended apt sources.list
      template:
        src: ../templates/sources.list
        dest: /etc/apt/sources.list

    - name: Update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true

    - name: Install packages
      apt:
        state: present
        name: [
          build-essential, openvpn, ffmpeg, adb, unrar, htop, vlc, transmission,
          nvidia-driver, ffmpeg, intel-microcode, curl, net-tools, deja-dup,
          chromium, vim, shotwell, picard
        ]

    - name: Install VirtualBox
      apt:
        deb: https://download.virtualbox.org/virtualbox/6.0.14/virtualbox-6.0_6.0.14-133895~Debian~buster_amd64.deb

    - name: Install Vagrant
      apt:
        deb: https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb

    - name: Install VeraCrypt
      apt:
        deb: https://launchpad.net/veracrypt/trunk/1.24-update4/+download/veracrypt-1.24-Update4-Debian-10-amd64.deb
