# run with `sudo ansible-playbook install-packages.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Copy extended apt sources.list
      template:
        src: ../templates/sources.list
        dest: /etc/apt/sources.list

    - name: Update and upgrade apt packages
      apt:
        upgrade: true
        update_cache: true

    - name: Install packages
      apt:
        state: present
        name: [
          build-essential, openvpn, ffmpeg, adb, unrar, htop, vlc, transmission,
          nvidia-driver, ffmpeg, intel-microcode, curl, net-tools
        ]