# run with `ansible-playbook robo3t.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Delete old Robo3t version
      file:
         path: ~/Apps/robo3t
         state: absent

    - name: Download Robo3t
      get_url:
        url: https://github.com/Studio3T/robomongo/releases/download/v1.3.1/robo3t-1.3.1-linux-x86_64-7419c406.tar.gz
        dest: ~/Downloads/robo3t.tar.gz

    - name: Extract Robo3t
      unarchive:
        src: ~/Downloads/robo3t.tar.gz
        dest: ~/Apps

    - name: Move Robo3t folder
      shell: mv ~/Apps/robo3t-* ~/Apps/robo3t

    - name: Symlink robo3t bin
      become: true
      file:
        src: /home/mustardamus/Apps/robo3t/bin/robo3t
        dest: /usr/bin/robo3t
        state: link

    - name: Remove archive
      file:
        path: ~/Downloads/robo3t.tar.bz2
        state: absent