# run with `sudo ansible-playbook sudo-passwordless.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Add config file to sudoers.d/
      lineinfile:
        path: /etc/sudoers.d/mustardamus
        line: "mustardamus ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"

    - name: Include sudoers.d/ in sudoers file
      lineinfile:
        dest: /etc/sudoers
        line: "#includedir /etc/sudoers.d"
        state: present
        validate: "visudo -cf %s"
