# run with `ansible-playbook visual-studio-code.yml`

---
- hosts: localhost
  connection: local
  tasks:
    - name: Install VS Code
      apt:
        deb: https://go.microsoft.com/fwlink/?LinkID=760868
      become: true

    - name: Create config folder
      file:
        path: ~/.config/Code/User
        state: directory

    - name: Copy settings
      copy:
        src: ../templates/visual-studio-code/settings.json
        dest: ~/.config/Code/User/settings.json

    - name: Copy keybindings
      copy:
        src: ../templates/visual-studio-code/keybindings.json
        dest: ~/.config/Code/User/keybindings.json

    - name: Install extensions
      shell: "code --install-extension {{item}}" # show with `code --list-extensions`
      with_items: [
        dbaeumer.vscode-eslint,
        dustinsanders.an-old-hope-theme-vscode,
        formulahendry.auto-close-tag,
        octref.vetur,
        steoates.autoimport,
        fayras.simple-new-file
      ]